// /properties/maintenance/work-orders/[id]/print — printable view ([G-B-28]).
// Renders a single-page summary the PM can hand to a vendor. Tailwind print:
// classes hide chrome; the browser print dialog fires via window.print().
"use client";

import * as React from "react";
import { useParams, notFound } from "next/navigation";

interface PartsRow {
  qty: number;
  accountId: string;
  description: string;
  price: number;
  total: number;
}
interface WoDetail {
  id: string;
  subject: string;
  vendorId: string;
  status: string;
  priority: string;
  dueDate: string | null;
  taskId: string;
  entryDetails: string | null;
  invoiceNumber: string;
  chargeWorkTo: { type: string; id: string } | null;
  workToBePerformed: string;
  vendorNotes: string;
  partsAndLabor: PartsRow[];
  billTotal: number;
  unitId: string | null;
  propertyId: string | null;
}

export default function WorkOrderPrintPage() {
  const { id } = useParams<{ id: string }>();
  const [doc, setDoc] = React.useState<WoDetail | null>(null);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => {
    fetch(`/api/pm/work-orders/${id}`).then(async (r) => {
      if (r.ok) setDoc((await r.json()) as WoDetail);
      setLoading(false);
    });
  }, [id]);

  React.useEffect(() => {
    if (doc) setTimeout(() => window.print(), 500);
  }, [doc]);

  if (loading) return <p className="p-8 text-sm">Loading…</p>;
  if (!doc) return notFound();

  return (
    <div className="mx-auto max-w-3xl space-y-6 p-8 print:p-4">
      <header className="border-b border-border pb-4">
        <h1 className="text-2xl font-bold text-fg">Work Order</h1>
        <p className="text-sm text-fg-muted">ID: {doc.id}</p>
      </header>

      <section className="space-y-2">
        <h2 className="text-lg font-bold text-fg">{doc.subject}</h2>
        <p className="text-sm text-fg-muted">
          Status: <strong>{doc.status}</strong> · Priority:{" "}
          <strong>{doc.priority}</strong>
        </p>
        {doc.dueDate && (
          <p className="text-sm text-fg-muted">
            Due: {new Date(doc.dueDate).toLocaleDateString()}
          </p>
        )}
      </section>

      <section className="space-y-1">
        <h3 className="text-sm font-bold uppercase tracking-widest text-fg-muted">
          Entry
        </h3>
        <p className="text-sm text-fg">{doc.entryDetails ?? "—"}</p>
      </section>

      <section className="space-y-1">
        <h3 className="text-sm font-bold uppercase tracking-widest text-fg-muted">
          Work to be performed
        </h3>
        <p className="whitespace-pre-line text-sm text-fg">
          {doc.workToBePerformed || "—"}
        </p>
      </section>

      <section className="space-y-1">
        <h3 className="text-sm font-bold uppercase tracking-widest text-fg-muted">
          Notes to vendor
        </h3>
        <p className="whitespace-pre-line text-sm text-fg">
          {doc.vendorNotes || "—"}
        </p>
      </section>

      <section className="space-y-1">
        <h3 className="text-sm font-bold uppercase tracking-widest text-fg-muted">
          Parts and labor
        </h3>
        {doc.partsAndLabor.length === 0 ? (
          <p className="text-sm text-fg-muted">None.</p>
        ) : (
          <table className="w-full border-collapse text-sm">
            <thead>
              <tr className="border-b border-border text-left text-xs uppercase">
                <th>Qty</th>
                <th>Description</th>
                <th>Price</th>
                <th>Total</th>
              </tr>
            </thead>
            <tbody>
              {doc.partsAndLabor.map((p, i) => (
                <tr key={i} className="border-b border-border/40">
                  <td>{p.qty}</td>
                  <td>{p.description}</td>
                  <td>${(p.price / 100).toFixed(2)}</td>
                  <td>${(p.total / 100).toFixed(2)}</td>
                </tr>
              ))}
            </tbody>
            <tfoot>
              <tr>
                <td colSpan={3} className="text-right font-bold">
                  Total
                </td>
                <td className="font-bold">
                  ${(doc.billTotal / 100).toFixed(2)}
                </td>
              </tr>
            </tfoot>
          </table>
        )}
      </section>

      <footer className="mt-12 border-t border-border pt-4 text-xs text-fg-muted">
        Generated by Property Management — print this page from your browser.
      </footer>
    </div>
  );
}
