/**
 * Reconciles which legal entity owns what, so the new per-company columns on
 * Financials have something true to render.
 *
 * THREE THINGS ARE WRONG AT ONCE and they are easy to confuse:
 *
 *  1. The P&L collapsed every Company-scoped row into one "Company" column.
 *     That was a REPORT bug and is fixed in app/api/pm/financials/matrix.
 *  2. Most Company-scoped rows carry `scopeId: null` — the legacy bucket,
 *     written before named companies existed. They name no entity at all, so
 *     no report can attribute them. That is a DATA gap, and this script is how
 *     you see it.
 *  3. `Property.companyAccountId` — which building belongs to which entity — is
 *     independently wrong or unset. That drives company-level cost allocation
 *     (lib/pm/companyProperties.ts), not the columns.
 *
 * WHAT THIS PROPOSES, AND WHAT IT REFUSES TO. A legacy row is re-scoped only
 * where the DATA already says which company it belongs to: it was generated by
 * a recurring rule that names one, or its memo matches such a rule exactly.
 * Everything else is listed as "needs a decision" and left alone.
 *
 * It will NEVER infer a company from a property's name. "IMMEUBLES GREENE" is
 * not evidence that a building belongs to Immeubles Greene Inc. — that is a
 * legal fact about who signed the deed, the client owns it, and guessing it
 * would silently move real money between entities' books.
 *
 * Dry-run by default. `--apply` writes ONLY the evidence-backed re-scopes.
 *   npx --yes tsx scripts/audit-company-scope.ts --org=<id>
 *   npx --yes tsx scripts/audit-company-scope.ts --org=<id> --apply
 */
import dns from "node:dns";
import { readFileSync } from "node:fs";
import { resolve as resolvePath } from "node:path";
import mongoose, { Types } from "mongoose";
import { connectToDatabase } from "../lib/db/mongoose";
import { Bill } from "../lib/db/models/pm/Bill";
import { CompanyAccount } from "../lib/db/models/pm/CompanyAccount";
import { JournalEntry } from "../lib/db/models/pm/JournalEntry";
import { Property } from "../lib/db/models/pm/Property";
import { RecurringTransaction } from "../lib/db/models/pm/RecurringTransaction";
import { normalizeScope, scopeCompanyIdOf } from "../lib/pm/scope";

function loadEnvLocal() {
  try {
    const raw = readFileSync(resolvePath(".env.local"), "utf8");
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^([A-Z0-9_]+)=(.*)$/);
      if (m && m[1] && process.env[m[1]] === undefined)
        process.env[m[1]] = m[2];
    }
  } catch {
    /* optional */
  }
}

function arg(name: string): string | null {
  const hit = process.argv.find((a) => a.startsWith("--" + name + "="));
  return hit ? hit.slice(name.length + 3) : null;
}

const ORG_ID = arg("org") ?? "6a15a84e5bac3c1113395eb4";
const APPLY = process.argv.includes("--apply");
const money = (c: number) => "C$" + (c / 100).toFixed(2);

/** Memos are hand-keyed, so compare on letters and digits only. */
function normaliseMemo(memo: string | null | undefined): string {
  return (memo ?? "").toUpperCase().replace(/[^A-Z0-9]/g, "");
}

async function main() {
  loadEnvLocal();
  const servers = process.env.MONGODB_DNS_SERVERS;
  if (servers) dns.setServers(servers.split(",").map((s) => s.trim()));
  await connectToDatabase();
  const orgObjectId = new Types.ObjectId(ORG_ID);

  console.log("MODE: " + (APPLY ? "APPLY (writing)" : "DRY RUN (no writes)"));
  console.log("ORG:  " + ORG_ID + "\n");

  const companies = await CompanyAccount.find({ organizationId: orgObjectId })
    .select({ _id: 1, name: 1, active: 1 })
    .sort({ name: 1 })
    .lean<Array<{ _id: Types.ObjectId; name: string; active: boolean }>>();
  const companyName = new Map(companies.map((c) => [String(c._id), c.name]));

  const properties = await Property.find({ organizationId: orgObjectId })
    .select({ _id: 1, propertyName: 1, companyAccountId: 1, active: 1 })
    .sort({ propertyName: 1 })
    .lean<
      Array<{
        _id: Types.ObjectId;
        propertyName?: string;
        companyAccountId?: Types.ObjectId | null;
        active: boolean;
      }>
    >();

  // ---- A. who owns what --------------------------------------------------
  console.log("=== A. Buildings by legal entity ===");
  for (const c of companies) {
    const owned = properties.filter(
      (p) => String(p.companyAccountId ?? "") === String(c._id),
    );
    console.log(
      "  " +
        c.name +
        (c.active ? "" : " (inactive)") +
        " — " +
        owned.length +
        " building(s)",
    );
    for (const p of owned) {
      console.log("      " + (p.propertyName ?? "(unnamed)"));
    }
    if (owned.length === 0) {
      console.log(
        "      ⚠ owns nothing — company-level costs scoped here cannot be allocated",
      );
    }
  }
  const orphanProps = properties.filter((p) => !p.companyAccountId);
  if (orphanProps.length > 0) {
    console.log(
      "  (no company assigned) — " + orphanProps.length + " building(s)",
    );
    for (const p of orphanProps) {
      console.log("      " + (p.propertyName ?? "(unnamed)"));
    }
  }
  console.log(
    "\n  Assign buildings in Settings → Companies → Assign buildings.\n" +
      "  This script will not guess it: which entity owns a building is a legal\n" +
      "  fact, not something a property name can be read for.\n",
  );

  // ---- B. legacy Company/null rows ---------------------------------------
  const rules = await RecurringTransaction.find({ organizationId: orgObjectId })
    .select({ _id: 1, memo: 1, amounts: 1 })
    .lean<
      Array<{
        _id: Types.ObjectId;
        memo?: string;
        amounts?: Array<{
          scopeType?: string;
          scopeId?: Types.ObjectId | null;
        }>;
      }>
    >();

  /** rule -> the single named company it posts to, when unambiguous. */
  const ruleCompany = new Map<string, string>();
  const ruleByMemo = new Map<string, string>();
  for (const r of rules) {
    const ids = new Set(
      (r.amounts ?? [])
        .map((a) => scopeCompanyIdOf(normalizeScope(a)))
        .filter((x): x is string => Boolean(x)),
    );
    if (ids.size === 1) {
      const only = Array.from(ids)[0]!;
      ruleCompany.set(String(r._id), only);
      const key = normaliseMemo(r.memo);
      if (key) {
        // An ambiguous memo is worse than no memo — mark it unusable.
        ruleByMemo.set(key, ruleByMemo.has(key) ? "" : only);
      }
    }
  }

  const bills = await Bill.find({
    organizationId: orgObjectId,
    "scope.type": "Company",
    "scope.id": null,
    status: { $ne: "Voided" },
  })
    .select({
      _id: 1,
      memo: 1,
      amount: 1,
      invoiceDate: 1,
      recurringTransactionId: 1,
    })
    .sort({ invoiceDate: 1 })
    .lean<
      Array<{
        _id: Types.ObjectId;
        memo?: string;
        amount: number;
        invoiceDate: Date;
        recurringTransactionId?: Types.ObjectId | null;
      }>
    >();

  console.log('=== B. Bills in the legacy "Company (unassigned)" bucket ===');
  console.log("  " + bills.length + " bill(s)\n");

  const evidenced: Array<{
    id: Types.ObjectId;
    companyId: string;
    why: string;
    memo: string;
  }> = [];
  const undecided: typeof bills = [];
  for (const b of bills) {
    let companyId: string | undefined;
    let why = "";
    if (b.recurringTransactionId) {
      companyId = ruleCompany.get(String(b.recurringTransactionId));
      if (companyId) why = "generated by a rule scoped to this company";
    }
    if (!companyId) {
      const hit = ruleByMemo.get(normaliseMemo(b.memo));
      if (hit) {
        companyId = hit;
        why = "memo matches a rule scoped to this company";
      }
    }
    if (companyId) {
      evidenced.push({ id: b._id, companyId, why, memo: b.memo ?? "" });
    } else {
      undecided.push(b);
    }
  }

  console.log("  -- can be attributed from the data --");
  for (const e of evidenced) {
    console.log(
      "    " +
        (companyName.get(e.companyId) ?? e.companyId).padEnd(18) +
        "  " +
        e.memo.slice(0, 46).padEnd(46) +
        "  (" +
        e.why +
        ")",
    );
  }
  if (evidenced.length === 0) console.log("    none");

  console.log("\n  -- needs a decision (no evidence in the data) --");
  const undecidedTotal = undecided.reduce((s, b) => s + (b.amount ?? 0), 0);
  for (const b of undecided.slice(0, 30)) {
    console.log(
      "    " +
        b.invoiceDate.toISOString().slice(0, 10) +
        "  " +
        money(b.amount).padStart(12) +
        "  " +
        (b.memo ?? "").slice(0, 50),
    );
  }
  if (undecided.length > 30) {
    console.log("    … and " + (undecided.length - 30) + " more");
  }
  console.log("    total " + money(undecidedTotal));
  console.log("");
  console.log(
    "    Note: the MORTGAGE bills above are attributed separately by",
  );
  console.log("    scripts/repair-mortgage-splits.ts, which matches them to a");
  console.log("    rule by payment amount. Their memos differ from the rule's");
  console.log('    by a stray letter ("IMM. GREEN &" vs "IMM GREENE &"), so');
  console.log("    memo matching cannot see them. Run that script first, then");
  console.log("    re-run this one.");

  // ---- C. ledger lines still unattributed --------------------------------
  const lineRows = await JournalEntry.aggregate<{
    _id: null;
    lines: number;
    debits: number;
  }>([
    {
      $match: {
        organizationId: orgObjectId,
        status: "Posted",
        reversesJournalEntryId: null,
      },
    },
    { $unwind: "$lines" },
    { $match: { "lines.scopeType": "Company", "lines.scopeId": null } },
    {
      $group: {
        _id: null,
        lines: { $sum: 1 },
        debits: { $sum: "$lines.debit" },
      },
    },
  ]);
  const summary = lineRows[0];
  console.log("\n=== C. Ledger lines still on the legacy bucket ===");
  console.log(
    "  " +
      (summary?.lines ?? 0) +
      " line(s), " +
      money(summary?.debits ?? 0) +
      " of debits.",
  );
  console.log(
    '  These render under "Company (unassigned)" on Financials until the\n' +
      "  bills above are attributed and their entries reposted.",
  );

  if (!APPLY) {
    console.log("\nDry run — nothing was written.");
    console.log(
      "Re-run with --apply to re-scope only the " +
        evidenced.length +
        " evidence-backed bill(s).",
    );
    return;
  }

  let written = 0;
  for (const e of evidenced) {
    await Bill.updateOne(
      { _id: e.id, organizationId: orgObjectId },
      { $set: { "scope.id": new Types.ObjectId(e.companyId) } },
    );
    written += 1;
  }
  console.log("\nRe-scoped " + written + " bill(s).");
  console.log(
    "Their journal entries still carry the old scope — repost each bill\n" +
      "(or run scripts/repair-mortgage-splits.ts for the mortgage ones) so the\n" +
      "ledger follows.",
  );
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(() => mongoose.disconnect());
